 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4444
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 779-241-359
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 4444 is in use by another program. Either identify and stop that program, or start the server with a different port.
Traceback (most recent call last):
  File "/Users/seungbeomha/AI_MLStudy/OpenSWLecture/app.py", line 68, in <module>
    app.run(port=4444, debug=True)
  File "/Users/seungbeomha/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/seungbeomha/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/werkzeug/serving.py", line 1090, in run_simple
    run_with_reloader(
  File "/Users/seungbeomha/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/werkzeug/_reloader.py", line 434, in run_with_reloader
    ensure_echo_on()
  File "/Users/seungbeomha/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/werkzeug/_reloader.py", line 414, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
